apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: rabbitmq-pvc-volume
 labels:
    type: local
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi