apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq-service
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-management
          ports:
            - containerPort: 5672 
          volumeMounts:
            - name: data-volume
              mountPath: /data/rabbitmq
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: rabbitmq-pvc-volume